### ISSUE TITLE
Crash after updating to release 1.2

### ISSUE THREAD

**Issue by jakub-gonet** [JakubekWeg/Mobishit#13]
As in title, app instantly crashes after start. Maybe it's connected with new exams fetching feature?

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:318)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)
Caused by: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
	at android.arch.b.b.h.e(Unknown Source)
	at android.arch.b.b.h.c(Unknown Source)
	at android.arch.b.a.a.b$a.onOpen(Unknown Source)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:266)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at android.arch.b.a.a.b$a.a(Unknown Source)
	at android.arch.b.a.a.b.a(Unknown Source)
	at android.arch.b.b.f.a(Unknown Source)
	at jakubweg.mobishit.db.g.a(Unknown Source)
	at jakubweg.mobishit.model.TimetableModel.f(Unknown Source)
	at jakubweg.mobishit.model.BaseViewModel$a.a(Unknown Source)
	at jakubweg.mobishit.model.BaseViewModel$a.doInBackground(Unknown Source)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

```

**Comment by JakubekWeg** [comment]
I know why it happened - I have changed the database's structure, but haven't add any migration, because it's a developer version. In official version (which is almost ready to be released) it clears database automatically and requests a new one by API, so users don't see that. Anyway, thanks for reporting😀

To use app just clear its data in settings and log in again.

**Comment by JakubekWeg** [comment]
BTW, how do you get the stack trace of a crash?

**Comment by jakub-gonet** [comment]
When app crashes on startup it shows from system popup, but in general case you want to setup logger and write debug info to some file and to stdout, so you can connect via `adb` and look into it.
